### ISSUE TITLE
Timelines around support for legacy Python

### ISSUE THREAD

**Issue by PeterJCLaw** [gristlabs/asttokens#107]
Just wondering what the plans were for keeping supporting running this package under legacy Python?

As demonstrated by https://github.com/gristlabs/asttokens/pull/106, doing so isn't free (even if it is relatively low effort), so it might be a good idea to consider dropping Python < 3.7 at some point.

It's worth noting that IPython, possibly the biggest package which depends in some form on `asttokens` hasn't supported < 3.5 for over 5 years now, which hopefully means that that isn't the driving reason to keep supporting the older versions.

**Comment by dsagal** [comment]
The driving force for supporting Python2 is actually Grist (https://github.com/gristlabs/grist-core), which was the driving force for creating `asttokens`. Specifically, the reason we need to keep supporting Python2 is that Grist has users with documents created when Python2 was still the default (this was in turn driven by a choice sandboxing that only worked with Python2).

If the pain of supporting both version were greater, we could update the major version of `asttokens`, drop Python2 support, and say that any packages that need it have to use an older `asttokens` version. At this point, this seems a greater hassle than supporting both Python2 and Python3 :)

**Comment by PeterJCLaw** [comment]
Thanks!
