### ISSUE TITLE
ModuleNotFoundError: No module named 'six.moves' with python 3.12

### ISSUE THREAD

**Issue by saiaprameya** [gristlabs/asttokens#133]
File "python3.12/site-packages/IPython/core/ultratb.py", line 104, in <module>
    import stack_data
  File "python3.12/site-packages/stack_data/__init__.py", line 1, in <module>
    from .core import Source, FrameInfo, markers_from_ranges, Options, LINE_GAP, Line, Variable, RangeInLine, \
  File "python3.12/site-packages/stack_data/core.py", line 16, in <module>
    from asttokens.util import Token
  File "python3.12/site-packages/asttokens/__init__.py", line 22, in <module>
    from .asttokens import ASTText, ASTTokens, supports_tokenless
  File "python3.12/site-packages/asttokens/asttokens.py", line 25, in <module>
    from six.moves import xrange  # pylint: disable=redefined-builtin
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'six.moves'

pip list | grep six
six                  1.15.0
pip list | grep asttokens
asttokens            2.4.1

**Comment by saiaprameya** [comment]
one observation is that when i run in python3.12
i see that:
import six
six.moves.xrange   starts working
but its not allowing to do from six.moves import xrange
which is a strange thing.

**Comment by alexmojaki** [comment]
Upgrade `six`

**Comment by saiaprameya** [comment]
Thanks Alex it worked.

**Comment by PeterJCLaw** [comment]
I think this suggests a bug in asttokens? If the package isn't specifying the right version/range of its dependencies then that's something we should probably fix.

**Comment by alexmojaki** [comment]
Yes but really we should review https://github.com/gristlabs/asttokens/pull/117 and get rid of six completely
