### ISSUE TITLE
ASTText: Module found error

### ISSUE THREAD

**Issue by XIE-ZJU** [gristlabs/asttokens#137]
Hi, thanks for you great job of this package. I met an error when I tried to install jupyter in the cloud sever with the following command: python -m ipykernel install --name pet-neus --user
It occured that ImportError: cannot import name 'ASTText' from 'asttokens' (/root/miniconda3/envs/pet-neus/lib/python3.8/site-packages/asttokens/__init__.py).
Thanks again, hope for you reply!

**Comment by R4M4KR15HN4** [comment]
pip install --upgrade asttokens
this solved my problem.

**Comment by evan-kolberg** [comment]
@R4M4KR15HN4 Thanks!

**Comment by XIE-ZJU** [comment]
Copy that!
