### ISSUE TITLE
RuntimeWarning: assigning None to unbound local

### ISSUE THREAD

**Issue by wyattscarpenter** [gristlabs/asttokens#148]
Hello,

Today I was running my program and I was greeted with the following runtime warnings:

```python
C:\[...]\.venv\Lib\site-packages\asttokens\util.py:173: RuntimeWarning: assigning None to unbound local 'n'
  if isinstance(c, type) and issubclass(c, ast.expr)} |
C:\[...]\.venv\Lib\site-packages\asttokens\util.py:173: RuntimeWarning: assigning None to unbound local 'c'
  if isinstance(c, type) and issubclass(c, ast.expr)} |
  ```

The program seems to work fine

I am using Python 3.12.5 (I think these warnings are new in 3.12) and asttokens  2.4.1.

Here's the line it's complaining about: https://github.com/gristlabs/asttokens/blob/2ff0e8d157fa89c22fe16839ab060b33f4c888bd/asttokens/util.py#L173

I submit this to you in case it helps you, or you know what it means, but I'm not holding my breath.

**Comment by alexmojaki** [comment]
If you can create a reproducible example, that'd be great. This might indicate a bug in CPython.

**Comment by wyattscarpenter** [comment]
That creating a repro will probably be very difficult, alas, because I don't really know the circumstances under which it's occurring the first time. (Your code is called by one of my dependencies, I think.) But I'll let you know if I figure one out!

**Comment by wyattscarpenter** [comment]
I opened a documentation [issue](https://github.com/python/cpython/issues/124118) about this to CPython, one thing led to another, and the fine folks there helped me figure out that it's my profiler causing the trouble, not your code. Sorry to bother you!
