### ISSUE TITLE
ValueError when parsing 

### ISSUE THREAD

**Issue by LiraNuna** [gristlabs/asttokens#2]
When parsing this valid code:

```python
[
    [
        1,
    ] for n in ()
]
```

A `ValueError` exception is raised:

```
ValueError: Expected token OP:'[', got ENDMARKER:'' on line 6 col 1
```

I believe it's related to #1 since removing the trailing comma does not throw, however I decided to file a separate issue just in case it's not.

**Comment by dsagal** [comment]
I checked that this is also fixed by the last commit, so closing.
