### ISSUE TITLE
get_text returns wrong result for `(lambda: 0)()`

### ISSUE THREAD

**Issue by alexmojaki** [gristlabs/asttokens#24]
First of all, great library! I'm using it for [this](https://github.com/alexmojaki/birdseye) and it's worked wonders for me.

Consider this script:

```python
import asttokens

tokens = asttokens.ASTTokens('(lambda: 0)()', parse=True)
call = tokens.tree.body[0].value
print(tokens.get_text(call))
```

The expected output is `(lambda: 0)()`, but the actual output is `(lambda: 0)`.

Strangely, there isn't a problem if you add an argument, e.g. `(lambda: 0)(1)`.

Of course this is a ridiculous way to use lambdas and if this is the only place this problem occurs I don't think it's worth fixing. I only came across this while playing with some nonsensical code. But I thought I should point it out in case there's an underlying problem that manifests in more serious ways.

**Comment by dsagal** [comment]
Oh wow, your project is beautiful!

Yeah, this seems to be one of those rare cases that the library doesn't get quite right. It decides which text is part of a function call by looking at the next closing paren after the last token it gets from `ast` (in this case, the "0"). If the function part of the call is wrapped in parentheses AND there are no arguments, then it messes up in the way you found. I think `(foo)()` would stop at `(foo)` too. It's possible to fix, but not trivial, and unclear if it's important.

**Comment by alexmojaki** [comment]
OK, that makes sense. With that explanation, I was able to come up with a more plausible (but still made up) scenario:

```python
import asttokens

source = """
x = (obj.attribute.get_callback()
     or default_callback)()
"""

tokens = asttokens.ASTTokens(source, parse=True)
call = tokens.tree.body[0].value
print(tokens.get_text(call))
```

Here parentheses are being used for implicit line continuation (I do this all the time) and `obj.attribute.get_callback()` might be `None`.

There's also the possibility that someone might have a callable expression wrapped in parentheses for no good reason, just as a mistake or a legacy of how the code previously was.

**Comment by alexmojaki** [comment]
>  It decides which text is part of a function call by looking at the next closing paren after the last token

Maybe the first thing it should do is look for the first opening paren, and then the closing one after that?

**Comment by dsagal** [comment]
You are right, the fix isn't hard, and the approach you suggested worked. I committed a fix and published a minor release with it.

**Comment by alexmojaki** [comment]
Awesome! Great turnaround time!
