### ISSUE TITLE
Debian package

### ISSUE THREAD

**Issue by aivarannamaa** [gristlabs/asttokens#26]
Hi!

First, thank you for this nice library! I wrote similar (but much more buggy) solution for my project (https://thonny.org), but now I'd like to replace my implementation with asttokens. At the same time I'd like to continue providing Debian package for my project and for this, all my dependencies should be also available in Debian repo.

Have you considered publishing asttokens on Debian? If you don't have time for this, then I could prepare the package myself and try to get it accepted. With luck it may be even possible to get it into upcoming Debian 10.

**Comment by dsagal** [comment]
Thank you! Indeed I don't know anything about publishing packages on Debian, so if you'd like to do it, you are more than welcome to. Let me know if I can help.

(BTW, Thonny looks like a very cool project!)

**Comment by aivarannamaa** [comment]
[Dominik George](https://github.com/Natureshadow) made the package and it is on its way towards Debian testing: https://tracker.debian.org/pkg/python-asttokens.
