### ISSUE TITLE
List comprehensions with numpy-like indexing raises ValueError

### ISSUE THREAD

**Issue by Varal7** [gristlabs/asttokens#32]
I am trying to parse the following minimal example:

```python
import numpy as np

xs = np.arange(8).reshape(2, 2, 2)
steps = 2

def get_steps(xs, steps):
    return [xs[:, step, :] for step in range(steps)]

print(get_steps(xs, steps))
```

I am using the following code

```python
import ast
import asttokens

code="""
import numpy as np

xs = np.arange(8).reshape(2, 2, 2)
steps = 2

def get_steps(xs, steps):
    return [xs[:, step, :] for step in range(steps)]

print(get_steps(xs, steps))
"""

def parse_ast(code):
    tree = ast.parse(code)
    return tree

def parse_asttokens(code):
    tree = asttokens.ASTTokens(code, parse=True).tree
    return tree


parse_ast(code)
parse_asttokens(code)
```

This fails with a `ValueError`: `Expected token OP:'[', got NAME:'return' on line 8 col 5`

I have tried looking at the internals of the the library but did not manage to understand why the `before` tokens falls out of the list comprehension

**Comment by Varal7** [comment]
Thanks for the fix! Testing on the train set (100k files) of the [150k Python dataset](https://www.sri.inf.ethz.ch/py150), it solves the bug for 15 files.

**Comment by dsagal** [comment]
Excellent! I published a patch version with this fix. Closing.
