### ISSUE TITLE
Parser does not handle Python3.6 f-strings

### ISSUE THREAD

**Issue by LiraNuna** [gristlabs/asttokens#4]
An exception is raised when trying to parse python3.6's [new f-strings](https://docs.python.org/3/reference/lexical_analysis.html#f-strings).

```
  File "ensure_trailing_commas/trailing_comma_finder.py", line 118, in find_missing_trailing_commas
    atok = asttokens.ASTTokens(source_code, parse=True)
  File "asttokens/asttokens/asttokens.py", line 61, in __init__
    self.mark_tokens(self._tree)
  File "asttokens/asttokens/asttokens.py", line 72, in mark_tokens
    MarkTokens(self).visit_tree(root_node)
  File "asttokens/asttokens/mark_tokens.py", line 47, in visit_tree
    util.visit_tree(node, self._visit_before_children, self._visit_after_children)
  File "asttokens/asttokens/util.py", line 148, in visit_tree
    pvalue, post_value = previsit(current, par_value)
  File "asttokens/asttokens/mark_tokens.py", line 51, in _visit_before_children
    token = self._code.get_token_from_utf8(node.lineno, col) if col is not None else None
  File "asttokens/asttokens/asttokens.py", line 123, in get_token_from_utf8
    return self.get_token(lineno, self._line_numbers.from_utf8_col(lineno, col_offset))
  File "asttokens/asttokens/line_numbers.py", line 48, in from_utf8_col
    return offsets[max(0, min(len(offsets), utf8_column))]
IndexError: list index out of range
```

**Comment by dsagal** [comment]
There is unfortunately an open bug in Python with annotating AST nodes from f-strings with proper line and column info: https://bugs.python.org/issue29051. In addition, the f-string literal is a single token, but the expressions inside would also need to be tokens: it would require some adjustments to when and how we parse tokens; in particular, the standard `tokenize` module does not currently help there.

I am open to proposals for how to handle it.

**Comment by LiraNuna** [comment]
I think there are two issues here: The exception and the lack of inside-tokens.
I would suggest starting by making the code not throw an exception on valid code.

It seems like even though fstrings are a single token, it should still be possible to use the locations given by the tokenizemodule:

```
$ python3.6 -m tokenize test2
0,0-0,0:            ENCODING       'utf-8'        
1,0-5,3:            STRING         "f'''\n{\nFOO\n}\n'''"
5,3-5,4:            NEWLINE        '\n'           
6,0-6,0:            ENDMARKER      ''
``` 

Maybe I'm not getting the bug, however

**Comment by dsagal** [comment]
Actually, could you share the full test case that produces the error. I am not seeing it with a just a single f-string literal.

**Comment by LiraNuna** [comment]
Okay so after experimentation it seems like this is a min case:

`f'{function(kwarg=24)}'`
will give:
```
  File "asttokens/line_numbers.py", line 48, in from_utf8_col
    return offsets[max(0, min(len(offsets), utf8_column))]
IndexError: list index out of range
```

**Comment by dsagal** [comment]
I pushed a fix to master, with a test case that includes your examples. The fix is simply to avoid descending inside an f-string, since we have neither locations nor tokens for the inner nodes.

Please check that it solves your issue. You can keep this bug open, or close and create a new one. Either way, the remaining bug is that asttokens does not include or annotate the AST subtrees inside fstrings.

**Comment by LiraNuna** [comment]
> The fix is simply to avoid descending inside an f-string

I'm guessing this explains this exception? `AttributeError: 'Call' object has no attribute 'first_token'` (Maybe assign `None` instead?)

That's a fair resolution for now since python lacks the ability to parse it. Hopefully when this issue resolves, this library would be able to improve.

Thanks for the fast resolution! 

P.S maybe a version bump is in order?

**Comment by dsagal** [comment]
Version bumped, and uploaded package with fix to pypi.
