### ISSUE TITLE
Misannotation of comma token type as 54 not 53 when running Python 3.8

### ISSUE THREAD

**Issue by lmmx** [gristlabs/asttokens#48]
Hi there, thanks so much for writing this library :smile: I've used it within my library [mvdef](https://github.com/lmmx/mvdef) to get per-token column/line locations for tasks like identifying exactly where names and commas are in import statements while walking the AST of a program, to then be able to rearrange, rewrite, and move those import statements and function definitions between files in a well-organised way.

While working with your library though (in fact, just at the point of testing it on the original application that made me set out to write the library in the first place – I didn't have any trouble whatsoever with asttokens before now), I encountered a bug, which I've managed to reproduce in Python 3.8 (not sure what might be causing that I'm afraid, the code in question being tokenised is fully 3.7 compliant).

It's not catastrophic, but when I processed the AST of a generated line of code, its tokenised representation had commas as type 54 not 53. I simply added a check in case the type was not 53 to look for type 54 and just continued with the code, like I say it's not a catastrophic error.

`asttokens.asttokens.token.tok_name` identifies these two different numbers as indicating:
- `53: 'OP'`
- `54: 'ERRORTOKEN'`

From my attempts to reproduce a minimal example, I think this only occurs with Python 3.8

Here is a sample run in a Python 3.7 conda env (i.e. note that `tko.tokens[4].type` is `53`)

```
>>> import asttokens
>>> mystr = "from A import B, C"
>>> tko = asttokens.ASTTokens(mystr)
>>> for t in tko.tokens: t
...
Token(type=1, string='from', start=(1, 0), end=(1, 4), line='from A import B, C', index=0, startpos=0, endpos=4)
Token(type=1, string='A', start=(1, 5), end=(1, 6), line='from A import B, C', index=1, startpos=5, endpos=6)
Token(type=1, string='import', start=(1, 7), end=(1, 13), line='from A import B, C', index=2, startpos=7, endpos=13)
Token(type=1, string='B', start=(1, 14), end=(1, 15), line='from A import B, C', index=3, startpos=14, endpos=15)
Token(type=53, string=',', start=(1, 15), end=(1, 16), line='from A import B, C', index=4, startpos=15, endpos=16)
Token(type=1, string='C', start=(1, 17), end=(1, 18), line='from A import B, C', index=5, startpos=17, endpos=18)
Token(type=4, string='', start=(1, 18), end=(1, 19), line='', index=6, startpos=18, endpos=18)
Token(type=0, string='', start=(2, 0), end=(2, 0), line='', index=7, startpos=18, endpos=18)
```

And here is the same code run in a Python 3.8 conda env (i.e. note that `tko.tokens[4].type` is `54`)

```
>>> import asttokens
>>> mystr = "from A import B, C"
>>> tko = asttokens.ASTTokens(mystr)
>>> for t in tko.tokens: t
... 
Token(type=1, string='from', start=(1, 0), end=(1, 4), line='from A import B, C', index=0, startpos=0, endpos=4)
Token(type=1, string='A', start=(1, 5), end=(1, 6), line='from A import B, C', index=1, startpos=5, endpos=6)
Token(type=1, string='import', start=(1, 7), end=(1, 13), line='from A import B, C', index=2, startpos=7, endpos=13)
Token(type=1, string='B', start=(1, 14), end=(1, 15), line='from A import B, C', index=3, startpos=14, endpos=15)
Token(type=54, string=',', start=(1, 15), end=(1, 16), line='from A import B, C', index=4, startpos=15, endpos=16)
Token(type=1, string='C', start=(1, 17), end=(1, 18), line='from A import B, C', index=5, startpos=17, endpos=18)
Token(type=4, string='', start=(1, 18), end=(1, 19), line='', index=6, startpos=18, endpos=18)
Token(type=0, string='', start=(2, 0), end=(2, 0), line='', index=7, startpos=18, endpos=18)
```

I hope this is enough info for you to investigate, and do let me know if I can supply any more info.

Thanks again for developing this library, I've been recommending it to other devs :+1:

**Comment by dsagal** [comment]
The explanation, I believe, is simple, although unsatisfying: "The specific numeric values which the names map to may change between Python versions." (from https://docs.python.org/3/library/token.html)

`OP` in 3.7: https://github.com/python/cpython/blob/3.7/Lib/token.py#L67 
`OP` in 3.8: https://github.com/python/cpython/blob/3.8/Lib/token.py#L60

**Comment by alexmojaki** [comment]
To clarify further, `asttokens.asttokens.token` is simply the built in `token` module, and in your code you should be using `token.OP` to check the type rather than a hardcoded number.

**Comment by alexmojaki** [comment]
Can we close this since it seems to be a non-issue?
