### ISSUE TITLE
Inability to set source filename

### ISSUE THREAD

**Issue by LiraNuna** [gristlabs/asttokens#8]
For tooling, it is important to have the file names in order to print warnings/errors.

Currently, `asttokens.ASTTokens` does not allow to pass in the file name it's parsing.

It should be possible to do that here: https://github.com/gristlabs/asttokens/blob/master/asttokens/asttokens.py#L49

**Comment by dsagal** [comment]
Seems like a good idea, I'd welcome a pull request.
