### ISSUE TITLE
`asttokens` 2.0.6 has undeclared dependency on `astroid`

### ISSUE THREAD

**Issue by domdfcoding** [gristlabs/asttokens#85]
Attempting to import `asttokens` when the `astroid` package is not installed results an a `ModuleNotFoundError`:

```python
$ python3 -c "import asttokens"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/tmp/asttokens-issue/venv/lib/python3.8/site-packages/asttokens/__init__.py", line 22, in <module>
    from .asttokens import ASTTokens
  File "/tmp/asttokens-issue/venv/lib/python3.8/site-packages/asttokens/asttokens.py", line 20, in <module>
    from .util import Token, match_token, is_non_coding_token, AstNode, patched_generate_tokens
  File "/tmp/asttokens-issue/venv/lib/python3.8/site-packages/asttokens/util.py", line 26, in <module>
    from astroid.node_classes import NodeNG  # type: ignore[import]
ModuleNotFoundError: No module named 'astroid'
```

`astroid` is not listed as a dependency in `setup.cfg`, only `six` and `typing`, so it does not get installed when `asttokens` is:

https://github.com/gristlabs/asttokens/blob/beb8a4edb8df3efae028b6b28d4beebd0c89c4fa/setup.cfg#L36-L38

**Comment by fcollonval** [comment]
We are hit in jupyterlab too by this one: https://github.com/jupyterlab/jupyterlab/runs/7727203699?check_suite_focus=true

As this is for typing, I would make it conditional.

**Comment by alexmojaki** [comment]
Released 2.0.7 which should work. Sorry everyone!

**Comment by alexmojaki** [comment]
@cdkini @blink1073 @tlambert03 @redeboer @gambolputty @0x26res @MaxVonKnobloch

**Comment by fcollonval** [comment]
Thanks a lot for the quick patch @alexmojaki
It fixes the error on JupyterLab.

**Comment by pllim** [comment]
Hello! Any plans to yank the buggy release?

**Comment by alexmojaki** [comment]
Thanks for the suggestion @pllim, 2.0.6 has been yanked.

**Comment by pllim** [comment]
Thank YOU for the quick fix!

**Comment by tlambert03** [comment]
Thanks a bunch!
